## NUMPY :---
--Numpy stands for the numerical python.
-- Numpy is a powerful libraries in the python.
-- It is mostely used for handelling the sets of numbers like array aor matrices
and performing the math operation on them.

## !PIP :---
--- Pip stands for the python installing packages.
--- it is a command that used for installing the libraries or packages like numpy ,-pandas etc in the python.

## ARRAY :---
-- Array is a collection of items or values that store in a single variable.
---All elements are arrany usually of the same data types.




In [1]:
## !pip   # when we dont have the librabry ,we need to install first //

In [2]:
## How to install pip ??

In [3]:
!pip install numpy   ## it is alredy installed that why showing requesiremenr satisfied.

In [4]:
## How to import

In [5]:
import numpy

In [8]:
import numpy as np  ## we do not always use numpy # we used as np ,use shortcut like// as--alias (as)

In [9]:
## Array :- Array is a collection of items or values that stored in a single variable.
# --- all elements are array usually of the same data types.
## 1D-- 1 DIMENSION // 2D --- 2 DIMENSION // 3D --- 3 DIMENSION .


## for creating array we used .np because without this we can not create array

In [12]:
arr=np.array([1,2,3,4,])  ##npis a method thats why we used parantheses braces(),we passed the list[]

In [13]:
arr  #1D

array([1, 2, 3, 4])

In [16]:
arr2 = np.array([[1,2,3],[4,5,6]])  # if we want to create a row and the coloum (2D)

In [17]:
arr2    ## we want to create both rows and coloumn (2D)

array([[1, 2, 3],
       [4, 5, 6]])

## ROW AND COLOUMN ALWAYS STARTS WITH ZERO (0) .

In [19]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])  ##3D

In [21]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## ARRAY ATTRIBUTION :-- we do not used any paranthesis
__ what is difference between method and attribution
--- in method we used . method name and paanthesis braces and
in attribution we do not use any parantheses.

# .ndim :--- number of dimension (to check how many dimension are availble )

In [40]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr3.ndim

2

.Shape :---  Shape show the how many rows and coloums are availble.

In [30]:
arr3.shape

(3, 3)

In [37]:
arr4=np.array([[1,2],[3,4],[5,6],[7,8]])

In [38]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
arr4.shape   # .shape checks how many rows and coloumn are availble.

(4, 2)

In [41]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## .Size :--  To check total number of elements.

In [42]:
arr4.size

8

In [43]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr3.size   ##Size :-- shows how many numbers are availble (in easy way)

9

In [45]:
arr

array([1, 2, 3, 4])

In [46]:
arr.size

4

## .Dtype :-- to check the type.

In [48]:
arr4.dtype

dtype('int64')

In [49]:
arr.dtype

dtype('int64')

In [50]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2.dtype

dtype('int64')

## MATRIX :----

In [54]:
np.zeros ((2,2))   ## Create a matrix  ## we always pass the diimension in paranthesis braces

array([[0., 0.],
       [0., 0.]])

In [77]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.ones((1,4))   ##ones :- kiti by kiti cha matrix pahije

array([[1., 1., 1., 1.]])

In [73]:
np.ones ((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## .EYE :--- Identify matrix // pass only single element

In [81]:
np.eye(2)   ## check the one and thir position // that is called eye(indentify the matrix)

array([[1., 0.],
       [0., 1.]])

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## .FULL :--- If we want to replace o by another number so we used .full

In [88]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [89]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [91]:
np.full((4,3),13)

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

## INDEXING AND SLICING [ ]:-  indexing and slicing are tools that allow us to access and extract specific parts of data from sequences, like lists, strings, or arrays.

--Always use square braces [ ]


-- INDEXING :--Accessing a single element.

-- SLICING  :-- Accessing multiple elemets.we give a range. we give a start and end value like [start:end]

In [95]:
arr

array([1, 2, 3, 4])

In [97]:
arr[2]  ## Indexing :-- Accessing single elemets ## tell the position of index ## need to put the index in square braces.

3

In [98]:
arr[3]

4

In [99]:
arr[0]

1

In [100]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr3[0]

array([1, 2, 3])

In [102]:
arr3[2]

array([7, 8, 9])

In [103]:
## SLICING  :--Accessing the range of the elements.

In [104]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [125]:
arr4[3:4] ## slicing :- acessing range of elements [start:end]

array([[7, 8]])

In [126]:
arr

array([1, 2, 3, 4])

In [129]:
arr[1:3]

array([2, 3])

In [137]:
### We want to indexing on two dimension .

In [139]:
arr7=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [140]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr7[2]  ##indexing

array([7, 8, 9])

In [142]:
arr7[0]

array([1, 2, 3])

In [143]:
arr7 [0:2]  ##slicing :-- if end with 2 then it will give the ouput of before the 2.

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
arr7[1:2]

array([[4, 5, 6]])

In [145]:
arr7[2:2]   ##can not show because value starts with 2 and ends with 2 ,so it is not possibl

array([], shape=(0, 3), dtype=int64)

## RESHAPING AND FLATTENING :== Reshaping and flattening are operations that help you change the structure of arrays in different ways.

## Reshaping :-Changes the structure or shape of the array without changing the data (e.g., from 1D to 2D or 3D).

for example :-you can change a 1D array (like a list) into a 2D array (like a grid or table), or change a 2D array into a 3D array.

In [146]:
arr=np.array([1,2,3,4,5,6])

In [147]:
arr

array([1, 2, 3, 4, 5, 6])

In [160]:
arr.ndim  ## ndim to check the dimension

1

In [163]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [164]:
arr.reshape(2,3)   ## 2 row, 3 coloumn

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [166]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## FLATTEN :---- Converts a multi-dimensional array into a 1D array .


In [168]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
arr7.flatten()   ## faltten convert multi-dimensional into 1d array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

In [173]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [174]:
arr4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])