### Import numpy is most important :-----
--- whenever we use the numpy ,it is very important to install the numpy first, without import we can not use the libraries (Numpy is the powerful libraries in python )

*   List item
*   List item



In [1]:
import numpy as np

## METHODS OF NUMPY :-----

## Arange () :-- arange() is useful when you need a series of numbers in a specific range with a specific step size.
--if we want a range from this to this (start to end) at that time we use the #arange method ().

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(5)   ## if want range always use .np

array([0, 1, 2, 3, 4])

In [29]:
np.arange(100)   ## we take range from 0 to n number.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
np.arange(2,5)   ##[start,end]  2 is start and 5 is end..it will starts from element 2.

array([2, 3, 4])

In [35]:
np.arange(100,500,2)  #(start,end,step)  # 2 is step

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306,
       308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332,
       334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358,
       360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384,
       386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410,
       412, 414, 416, 418, 420, 422, 424, 426, 428, 430, 432, 434, 436,
       438, 440, 442, 444, 446, 448, 450, 452, 454, 456, 458, 46

In [36]:
np.arange(1,100,10) (start,end,step)   # 10 is step

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Linspace ():--- that generates a sequence of numbers evenly spaced between two values.
----- (start,end,space)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.linspace(2,10,15)    ## 2 is start , 10 is end and 15 is space.

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [42]:
np.linspace(10,20,30)

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [44]:
arr2 = np.array([3,1,9,8,6,4])

## .SORT () :--- It sort the elements in an ascending order.

In [50]:
arr2

array([3, 1, 9, 8, 6, 4])

In [52]:
np.sort(arr2)   ##sort data in ascending order.

array([1, 3, 4, 6, 8, 9])

## Inbult function in numpy
 1) .Max (array name) :-- it gives max elements from the entire list/tuple.(np.max)

 2) .Min (array name) :-- it gives min elements from the entire list/tuple.(np.min)

 3) .Sum (array name :-- It will give sum of entire elements from the list/ tuple. (np.sum)

 4).Unique (arrany name ):- Ignore the duplicate elements.(np.unique)

In [61]:
arr3 = np.array([1,2,2,3,4,4,6,7,6])

In [62]:
arr3

array([1, 2, 2, 3, 4, 4, 6, 7, 6])

In [63]:
np.max(arr3)  ## max is inuilt fucntion

7

In [66]:
np.min(arr3)   ##min is inbult fucntion.

1

In [68]:
np.sum(arr3)  ## give sum of entire elements and its inbuilt funnction.

35

In [70]:
np.unique(arr3)   ##ignore the duplicates elements.

array([1, 2, 3, 4, 6, 7])

## STASTICAL MEASURE ARE MEAN ,MEDIAN AND MODE

1) MEAN :-- The mean is commonly used in data analysis to find the "central" value of a set of numbers.

rough:-- first create arry and then find the mean.


In [71]:
arr3

array([1, 2, 2, 3, 4, 4, 6, 7, 6])

In [73]:
np.mean(arr3)

3.888888888888889

In [74]:
arr2

array([3, 1, 9, 8, 6, 4])

In [76]:
np.mean(arr2)

5.166666666666667

2 ) MEDIAN :-- We use the median when we want to find the middle value of a set of numbers, especially when the data includes extreme values (outliers).

what is outliers :-- its like odd one out.(An outlier is a number in a set of data that is much larger or smaller than the other numbers)

In [77]:
arr3

array([1, 2, 2, 3, 4, 4, 6, 7, 6])

In [78]:
np.median(arr3)

4.0

In [79]:
arr2

array([3, 1, 9, 8, 6, 4])

In [80]:
np.median(arr2)

5.0

3) MODE :--- The mode when we want to find the most frequent value in a dataset. It helps us understand which value is most common.

-- For mode ,we need to first import the library like scipy (Scirntific python)


In [83]:
from scipy import stats   ## importing the scipy

In [84]:
arr3

array([1, 2, 2, 3, 4, 4, 6, 7, 6])

In [85]:
stats.mode(arr3)

ModeResult(mode=2, count=2)

In [86]:
stats.mode(arr2)

ModeResult(mode=1, count=1)

## VARIENCE :-- TO UNDERSTAND THE DATA SPREAD

-- Varience understand that how much number differ from the avaerage value in your data.

1) If number are close to the average that mean varience is low.

2)If number are far away from the average that mean varience is high.

In [6]:
import numpy as np

In [8]:
arr4 = np.array([1,5,6,3,8,9])

In [9]:
arr4

array([1, 5, 6, 3, 8, 9])

In [10]:
np.var(arr4)

7.5555555555555545

## STANDARD DEVIATION :-- Standard deviation is just another way to measure how spread out the numbers from the avaerage but it brings the value back to the same units,so its easy to understand.

# DIFFERENCE BETWEEN VARIENCE AND THE STANDARD DEVIATION ?

1) Varience :- Variance is in squared units (for example, if your data is in meters, variance will be in meters squared).

2) Standard deviation is in the same units as the data (if your data is in meters, standard deviation is also in meters).

In [11]:
arr4

array([1, 5, 6, 3, 8, 9])

In [12]:
np.std(arr4)

2.748737083745107

## Correlation Coefficient :--- TO UNDERSTAND RELATIONSHIP BETWEEN THE DIFFERET VARIABLES

-- The coefficient of correlation undersatnd that how strongly two things (variables) are connected.

In [15]:
arr4

array([1, 5, 6, 3, 8, 9])

In [16]:
np.corrcoef(arr4)

1.0

### PERCENTILE :--- Divide the data into 100 equal parts.

--Percentiles help break down data and see the spread of values. (पर्सेंटाइल डेटा को तोड़ने और इसके वैल्यूज के फैलाव (spread) को समझने में मदद करते हैं।)

--1st quartile (25%)(Q1)

-- 2nd quartile (50%)(Q2)

-- 3rd quartile (75%)(Q3)

-- IQR (interquartile range)= Q3-Q1

In [25]:
arr4

array([1, 5, 6, 3, 8, 9])

In [26]:
np.percentile(arr4,25)

3.5

In [28]:
np.percentile(arr4,50)

5.5

In [29]:
np.percentile(arr4,75)

7.5

In [30]:
np.percentile(arr4,75)-np.percentile(arr4,25)

4.0

## COVARIENCE :--- If you have two sets of data, covariance helps to show if they both move in the same direction or in opposite directions.

In [37]:
x=np.array([1,2,3,4,5])
y=np.array([2,5,9,7,8])

In [38]:
np.cov(x,y)

array([[2.5, 3.5],
       [3.5, 7.7]])

In [49]:
np.random.randint(0,50,5)

array([27, 45, 15, 36, 37])

## .RANDOM :--- Random in Python is used to generate random numbers or make random choices from a list.like randomly picking a number or shuffling items.

## RANDOM FUNCTION :---
1) .random.rand() :-- Get a random float between 0 and 1.

2) .random.randint(a,b) :-Get a random integer between a and b

3) np.random.randn :--- for normal(n) disctribution.

In [52]:
np.random.rand(10)   # Get a random float between 0 and 1.

array([0.44950311, 0.58751577, 0.52663042, 0.49622387, 0.51359757,
       0.62320091, 0.01107503, 0.80072656, 0.31823382, 0.90310068])

In [65]:
np.random.randint(1,100)

67

In [68]:
np.random.randn(2)

array([-0.86576891, -0.38373731])